// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import accountpoolmetrics "github.com/Optum/dce/pkg/accountpoolmetrics"
import mock "github.com/stretchr/testify/mock"

// AtomicWriter is an autogenerated mock type for the AtomicWriter type
type AtomicWriter struct {
	mock.Mock
}

// Decrement provides a mock function with given fields: name
func (_m *AtomicWriter) Decrement(name accountpoolmetrics.MetricName) error {
	ret := _m.Called(name)

	var r0 error
	if rf, ok := ret.Get(0).(func(accountpoolmetrics.MetricName) error); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Increment provides a mock function with given fields: name
func (_m *AtomicWriter) Increment(name accountpoolmetrics.MetricName) error {
	ret := _m.Called(name)

	var r0 error
	if rf, ok := ret.Get(0).(func(accountpoolmetrics.MetricName) error); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
